export const HTTP_STATUS = Object.freeze({
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    PAYLOAD_TOO_LARGE: 413,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
});

export const ERROR_TYPES = Object.freeze({
    AUTHENTICATION_REQUIRED: 'authentication_required',
    INVALID_API_KEY: 'invalid_api_key',
    API_KEY_EXPIRED: 'api_key_expired',
    API_KEY_REVOKED: 'api_key_revoked',
    BAD_REQUEST: 'bad_request',
    PAYLOAD_TOO_LARGE: 'payload_too_large',
    VALIDATION_ERROR: 'validation_error',
    UNSUPPORTED_FORMAT: 'unsupported_format',
    MODEL_NOT_FOUND: 'model_not_found',
    TARGET_DISABLED: 'target_disabled',
    TIER_EXHAUSTED: 'tier_exhausted',
    MODEL_QUEUE_TIMEOUT: 'model_queue_timeout',
    RATE_LIMIT_EXCEEDED: 'rate_limit_exceeded',
    BUDGET_EXCEEDED: 'budget_exceeded',
    CONTENT_BLOCKED: 'content_blocked',
    LOOP_DETECTED: 'loop_detected',
    PROVIDER_AUTH_ERROR: 'provider_auth_error',
    PROVIDER_RATE_LIMITED: 'provider_rate_limited',
    PROVIDER_QUOTA_EXHAUSTED: 'provider_quota_exhausted',
    PROVIDER_CONTENT_POLICY: 'provider_content_policy',
    PROVIDER_MODEL_NOT_FOUND: 'provider_model_not_found',
    PROVIDER_TIMEOUT: 'provider_timeout',
    PROVIDER_UNAVAILABLE: 'provider_unavailable',
    PROVIDER_SERVER_ERROR: 'provider_server_error',
    PROVIDER_ACCOUNTS_EXHAUSTED: 'provider_accounts_exhausted',
    MIDDLEWARE_ABORT_ERROR: 'middleware_abort_error',
    CONFIGURATION_ERROR: 'configuration_error',
    INTERNAL_ERROR: 'internal_error',
    NOT_FOUND: 'not_found',
    FORBIDDEN: 'forbidden',
    CONFLICT: 'conflict',
    NOT_IMPLEMENTED: 'not_implemented',
    DISCOVERY_ERROR: 'discovery_error',
    OAUTH_ERROR: 'oauth_error',
    OAUTH_CALLBACK_ERROR: 'oauth_callback_error',
    OAUTH_POLL_ERROR: 'oauth_poll_error',
    UNKNOWN: 'unknown',
});

export const ERROR_MESSAGES = Object.freeze({
    MISSING_BEARER_TOKEN: 'Missing bearer token',
    INVALID_API_KEY: 'Invalid API key',
    API_KEY_EXPIRED: 'API key has expired',
    API_KEY_REVOKED: 'API key has been revoked',
    BAD_REQUEST: 'Bad request',
    PAYLOAD_TOO_LARGE: 'Request body is too large',
    VALIDATION_FAILED: 'Validation failed',
    UNSUPPORTED_INGRESS_FORMAT: 'Unsupported ingress format',
    RATE_LIMIT_EXCEEDED: 'Rate limit exceeded',
    AGENT_LOOP_DETECTED: 'Agent loop detected',
    PROVIDER_AUTHENTICATION_FAILED: 'Provider authentication failed',
    MIDDLEWARE_ABORT: 'Middleware abort',
    CONFIGURATION_ERROR: 'Configuration error',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    NOT_FOUND: 'Not found',
    FORBIDDEN: 'Forbidden',
    DASHBOARD_READ_FAILED: 'Failed to read dashboard',
    DASHBOARD_NOT_FOUND_TEXT:
        'Dashboard not found. Run the build step or check DASHBOARD_STATIC_DIR.',
    BACKEND_CATALOG_NOT_INITIALIZED: 'Backend catalog not initialized',
});

export const HEADER_NAMES = Object.freeze({
    ACCEPT: 'Accept',
    AUTHORIZATION: 'Authorization',
    CACHE_CONTROL: 'Cache-Control',
    CONTENT_LENGTH: 'Content-Length',
    CONTENT_TYPE: 'Content-Type',
    RETRY_AFTER: 'Retry-After',
    SET_COOKIE: 'Set-Cookie',
    X_REQUEST_ID: 'X-Request-Id',
});

export const CONTENT_TYPES = Object.freeze({
    JSON: 'application/json',
    JSON_UTF8: 'application/json; charset=utf-8',
    HTML_UTF8: 'text/html; charset=utf-8',
    TEXT_PLAIN_UTF8: 'text/plain; charset=utf-8',
    FORM_URLENCODED: 'application/x-www-form-urlencoded',
    EVENT_STREAM: 'text/event-stream',
    OCTET_STREAM: 'application/octet-stream',
});

export const PROVIDER_NETWORK_ERROR_CODES = Object.freeze({
    TIMEOUT: Object.freeze([
        'ETIMEDOUT',
        'ESOCKETTIMEDOUT',
        'UND_ERR_CONNECT_TIMEOUT',
    ]),
    UNAVAILABLE: Object.freeze(['ECONNREFUSED', 'ENOTFOUND']),
});

export const PROVIDER_MESSAGE_HINTS = Object.freeze({
    QUOTA: Object.freeze([
        'quota',
        'premium',
        'limit exceeded',
        'billing_hard_limit_reached',
        'insufficient_quota',
    ]),
    CONTENT_POLICY: Object.freeze([
        'content',
        'content policy',
        'policy',
        'filter',
        'guardrail',
        'safety',
    ]),
});
